config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  
  delete "/bookmarks/:id", to: "bookmarks#destroy", as: :delete_bookmark
  # resources :bookmarks, only: [:destroy] as del_bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to movie_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list_id), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
 before_action :find_list, only: [:show]
  def index
    @lists = List.all
  end
  
  def show
    @bookmarks = @list.bookmarks
  end
  
  def new
    @list = List.new
  end
  
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

private
  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= render "form", bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for (list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner">
  <div class="container">
    <h1>Create your custom lists with your favorite movies!</h1>
  </div>
</div>
<div class="container">
<div class="title-container">
  <h2>My lists</h2>
  <%= link_to "Create a movie list", new_list_path(@list), class: "btn btn-flat" %>
</div>
  <div class="grid-container">
      <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <p><%= link_to list.name, list_path(list) %></p></div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<ul class="list-group">
  <% @bookmarks.each do |bookmark| %>
    <li class="list-group-item"><%= bookmark.movie.title %></li>
    <li class="list-group-item"><%= bookmark.movie.rating %></li>
    <li class="list-group-item"><%= bookmark.movie.overview %></li>
    <li class="list-group-item"><%= bookmark.comment %></li>
    <%= link_to "delete", delete_bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <% end %>
</ul>